# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NPDemoProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# swift
pod 'RxSwift'
pod 'RxCocoa'
pod 'Kingfisher'
pod 'SnapKit'
pod 'IQKeyboardManagerSwift'
pod 'ObjectMapper'

#oc
pod 'CYLTabBarController'
pod 'LYEmptyView'

end
